name: DanielleMcDonnell
favicon: null
layout_spectrum: 0.987914401339367
typography_spectrum: 0.07014376833103597
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7498838524334133
  lightness: 0.5389581674244255
  saturation: 0.5463747375179082
  rhythmicContrast: 0.9959710377734154
purpose: []
